# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Flash Chat iOS13' do
	
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'GoogleUtilities', :modular_headers => true
	pod 'FirebaseCore', :modular_headers => true
	pod 'IQKeyboardManagerSwift'
end
